name: OneNav
version: 1.2.2
slug: onenav
codenotary: wghaos@163.com
description: '可帮助你将浏览器书签集中式管理'
url: https://github.com/waxgourd-ha/waxgourd-addons
image: wghaos/onenav
init: false
arch:
  - aarch64
  - amd64
webui: "http://[HOST]:[PORT:8880]/"
ports:
  '80': 8880
backup_exclude:
  - '*/data/'
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/net/tun
ingress: false
ingress_stream: false
panel_icon: mdi:network
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
startup: services
boot: manual
apparmor: true
