name: "BleachWRT Plus"
version: "20250924"
slug: "bleachwrt_plus"
description: "BleachWRT Plus - 提供旁路由管理功能，集成WEB管理界面"
url: "https://gitcode.com/waxgourd/addons"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
ports:
  80/tcp: 80
ports_description:
  80/tcp: "WEB服务端口"
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - SYS_MODULE
  - NET_RAW
webui: "http://[HOST]:[PORT:80]/"
watchdog: "http://[HOST]:[PORT:80]/"
apparmor: false
options:
  virtual_ip: 192.168.68.111
  netmask: 255.255.255.0
  gateway: 192.168.68.1
  enable_forwarding: true
  log_level: "info"
schema:
  virtual_ip: str
  netmask: str
  gateway: str
  enable_forwarding: bool
  log_level: list(info|debug)
image: wghaos/bleachwrt-{arch}
