name: '冬瓜伴侣代理'
version: '1.0.3'
slug: 'wghaos-mate'
codenotary: 'wghaos@163.com'
description: "专门为远程访问冬瓜伴侣制作的代理"
url: https://github.com/waxgourd-ha/waxgourd-addons
image: wghaos/addons-wghaos-meta
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 8124
ingress_entry: "home/#/dashboard"
panel_icon: 'mdi:application-variable'
host_network: true
boot: manual
environment:
  TZ: "Asia/Shanghai"
hassio_api: true