name: Openlist
slug: openlist
description: 'OpenList 是一个有韧性、长期治理、社区驱动的 AList 分支，旨在防御基于信任的开源攻击'
url: https://github.com/waxgourd-ha/waxgourd-addons
version: 4.1.5
image: wghaos/addons-wghaos-openlist
codenotary: wghaos@163.com
arch:
  - aarch64
  - amd64
apparmor: true
backup_exclude:
  - '*/data/'
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/net/tun
webui: "[PROTO:http]://[HOST]:[PORT:5244]"
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
init: false
ports:
  5244/tcp: 5244
ports_description:
  '5244': web port
startup: application
boot: manual
